# config/packages/reset_password.yaml
symfonycasts_reset_password:
    request_password_repository: App\Repository\User\Reset\ResetPasswordRequestRepository
    lifetime: 300
    throttle_limit: 10
    enable_garbage_collection: false