# config/services.yaml
services:

    twig.extension.date:
      class: Jasny\Twig\DateExtension
      tags:
        - { name: twig.extension }

    twig.extension.pcre:
      class: Jasny\Twig\PcreExtension
      tags:
        - { name: twig.extension }

    twig.extension.text:
      class: Jasny\Twig\TextExtension
      tags:
        - { name: twig.extension }

    twig.extension.array:
      class: Jasny\Twig\ArrayExtension
      tags:
        - { name: twig.extension }


    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # custom services
    # App\EventListener\ExceptionListener:
    #     tags:
    #       - { name: kernel.event_listener,  event: kernel.exception, priority: 10 }

    # Search
    App\Entity\NoMap\Search\Search:
        autowire: true

    # ResetPasswordEmailer
    App\Emailer\Profile\ResetPassword\ResetPasswordEmailer:
        autowire: true

    # DeleteAccountInfoEmailer
    App\Emailer\Profile\DeleteAccount\DeleteAccountInfoEmailer:
        autowire: true

    # RegisterUserConfirmEmailer
    # App\Controller\Emailer\DeleteAccount\RegisterUserConfirmEmailer:
    #     autowire: true

    # Admin Paginator
    App\Controller\Admin\Paginator\Paginator:
        autowire: true

    # the `qipsius.tcpdf` service will be injected when a
    # `Qipsius\TCPDFBundle\Controller\TCPDFController` type-hint is detected
    Qipsius\TCPDFBundle\Controller\TCPDFController: '@qipsius.tcpdf'

    # MaxItems Service
    App\Service\MaxItemsService:
      arguments:
        $cache: '@cache.app'
        $logger: '@logger'

    # Filter Aggregation Service
    App\Service\FilterAggregationService:
      arguments:
        $logger: '@logger'

    # Price Filter Service
    App\Service\PriceFilterService: ~

    # Product Listing Service
    App\Service\ProductListingService:
      arguments:
        $paginator: '@knp_paginator'
        $logger: '@logger'

    # Static Filters Service
    App\Service\StaticFiltersService:
      arguments:
        $cache: '@cache.app'
        $logger: '@logger'

    # Attribute Service
    App\Service\AttributeService:
      arguments:
        $cache: '@cache.app'
        $cachePool: '@cache.app'
        $projectDir: '%kernel.project_dir%'
      tags:
          - { name: cache.taggable }

    # Repositories
    App\Repository\User\Settings\MaxItemsRepository:
      arguments:
        $logger: '@logger'




    # App\Service\AttributeService:
    #     arguments:
    #         $projectDir: '%kernel.project_dir%'
    #     tags:
    #         - { name: cache.taggable }


parameters:
  app.max_items.listing: '%env(int:APP_MAX_ITEMS_LISTING)%'
  app.max_items.detail: '%env(int:APP_MAX_ITEMS_DETAIL)%'
  app.max_items.search: '%env(int:APP_MAX_ITEMS_SEARCH)%'
  app.max_items.api: '%env(int:APP_MAX_ITEMS_API)%'


# # This file is the entry point to configure your own services.
# # Files in the packages/ subdirectory configure your dependencies.
#
# # Put parameters here that don't need to change on each machine where the app is deployed
# # https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# parameters:
#
# services:
#     # default configuration for services in *this* file
#     _defaults:
#         autowire: true      # Automatically injects dependencies in your services.
#         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
#
#     # makes classes in src/ available to be used as services
#     # this creates a service per class whose id is the fully-qualified class name
#     App\:
#         resource: '../src/'
#
#     # add more service definitions when explicit configuration is needed
#     # please note that last definitions always *replace* previous ones
